#!/usr/bin/env bash
# Durable installer for the internal speakers of the ASUS ProArt PX13 (TAS2783).
# For STOCK kernels >= 7.1 (upstream tas2783 driver). Run as a normal user;
# it asks for sudo when it needs it.
#
#   bash install-durable.sh
#
# SKU-independent by design: the ALSA card index, the card long name, the ACP
# PCI address and the PipeWire card name are all PROBED at install time. An
# earlier version hardcoded them for a HN7306EAC and failed silently on every
# other SKU (HN7306EA, HN7306EA-LX005X) - see lib/px13-detect.sh.
#
# Escape hatches (rarely needed): PX13_CARD, PX13_LONGNAME, PX13_DRIVER.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/px13-detect.sh
. "$REPO/lib/px13-detect.sh"

UCM="${UCM_DIR:-/usr/share/alsa/ucm2}"
DKMS_NAME=snd-soc-tas2783-sdw-px13
DKMS_VER=1.0
KREL="$(uname -r)"
MARKER="px13-audio-fix"

fail() { echo; echo "FAILED: $*" >&2; exit 1; }

echo "==> 0/8 Detecting the hardware (nothing below is hardcoded)"
CARD="$(px13_find_card)" || fail "no SoundWire ALSA card found.
    'cat /proc/asound/cards' shows no card whose driver mentions soundwire.
    Is snd_pci_ps loaded? Is this really a SoundWire machine?"
DRIVER="$(px13_card_driver "$CARD")" || fail "could not read the ALSA driver name of card $CARD"
LONG="$(px13_card_longname "$CARD")" || fail "could not read the CardLongName of card $CARD.
    UCM keys its override file on that exact string; without it nothing can be installed."
COMPONENTS="$(px13_card_components "$CARD")"

printf '    card index    : %s\n'   "$CARD"
printf '    ALSA driver   : %s\n'   "$DRIVER"
printf '    CardLongName  : %s\n'   "$LONG"
printf '    components    : %s\n'   "${COMPONENTS:-(empty)}"
printf '    UCM override  : %s\n'   "$UCM/conf.d/$DRIVER/$LONG.conf"

px13_has_tas2783 "$CARD" || fail "no TAS2783 amplifier found on this machine.
    Neither a 'tas2783-*' mixer control nor a TI (0102) SoundWire peripheral is
    present. This repo would not fix anything here."

[ -f "$UCM/conf.d/$DRIVER/$DRIVER.conf" ] || fail "base UCM config not found:
    $UCM/conf.d/$DRIVER/$DRIVER.conf
    The override includes it. Install/upgrade alsa-ucm-conf (>= 1.2.13)."

echo "==> 1/8 Kernel module with the 'Channel Playback' control (needs sudo)"
if command -v dkms >/dev/null 2>&1; then
  # drop an older manual install so it does not compete with the dkms one
  sudo rm -f "/usr/lib/modules/$KREL/updates/snd-soc-tas2783-sdw.ko"
  sudo mkdir -p "/usr/src/$DKMS_NAME-$DKMS_VER"
  sudo cp -f "$REPO/module/tas2783-sdw.c" "$REPO/module/tas2783.h" \
             "$REPO/module/Makefile" "$REPO/module/dkms.conf" \
             "/usr/src/$DKMS_NAME-$DKMS_VER/"
  sudo dkms install --force "$DKMS_NAME/$DKMS_VER" -k "$KREL"
  echo "    OK via DKMS (rebuilds itself on every kernel update)"
else
  echo "    dkms not found - manual build (redo it after every kernel update!)"
  ( cd "$REPO/module" && make KVER="$KREL" LLVM=1 )
  sudo install -Dm644 "$REPO/module/snd-soc-tas2783-sdw.ko" \
       "/usr/lib/modules/$KREL/updates/snd-soc-tas2783-sdw.ko"
  sudo depmod -a "$KREL"
fi

echo "==> 2/8 UCM blocks (needs sudo)"
OVERRIDE="$UCM/conf.d/$DRIVER/$LONG.conf"
TMP="$(mktemp)"; trap 'rm -f "$TMP"' EXIT
sed -e "s|@DRIVER@|$DRIVER|g" -e "s|@LONGNAME@|$LONG|g" \
    "$REPO/configs/ucm-card-override.conf.in" > "$TMP"
sudo install -Dm644 "$REPO/configs/sof-soundwire_tas2783.conf" "$UCM/sof-soundwire/tas2783.conf"
sudo install -Dm644 "$REPO/configs/codecs_tas2783_init.conf"   "$UCM/codecs/tas2783/init.conf"
sudo install -Dm644 "$TMP" "$OVERRIDE"
echo "    OK (unowned override in conf.d/$DRIVER/ -> survives package updates)"

# An override installed under a DIFFERENT long name (e.g. copied from a
# HN7306EAC guide onto a HN7306EA) is dead weight: UCM never reads it. Remove
# the ones this repo wrote, keep everything else untouched.
for f in "$UCM/conf.d/$DRIVER"/*.conf; do
  [ -f "$f" ] || continue
  [ "$f" = "$OVERRIDE" ] && continue
  if grep -q "$MARKER" "$f" 2>/dev/null; then
    sudo rm -f "$f"
    echo "    removed stale override for another SKU: $(basename "$f")"
  fi
done

# Detection helper + a cache of the values that are hard to probe once the
# hardware has already fallen off the bus (used by the resume recovery).
sudo install -Dm644 "$REPO/lib/px13-detect.sh" /usr/local/lib/px13-audio-detect.sh
PCI="$(px13_acp_pci)" || PCI=""
printf '# generated by px13-audio-fix on %s - do not edit by hand\nPX13_ACP_PCI=%s\nPX13_CARD_LONGNAME=%s\n' \
  "$(date '+%F %T')" "$PCI" "$LONG" | sudo tee /etc/px13-audio-fix.conf >/dev/null
echo "    cached: ACP PCI=${PCI:-?} -> /etc/px13-audio-fix.conf"

echo "==> 3/8 Activating the fixed module"
NEED_REBOOT=0
if ! amixer -D "hw:$CARD" controls 2>/dev/null | grep -q 'Channel Playback'; then
  systemctl --user stop wireplumber pipewire pipewire-pulse 2>/dev/null || true
  if sudo modprobe -r snd_soc_tas2783_sdw 2>/dev/null && sudo modprobe snd_soc_tas2783_sdw; then
    echo "    module reloaded live"
    sleep 2
  else
    NEED_REBOOT=1
    echo "    could not reload live - REBOOT at the end"
  fi
else
  echo "    control already present (fixed module already loaded)"
fi

echo "==> 4/8 Validating the UCM parse (must list 'Speaker')"
UCM_DEVS="$(alsaucm -c "$CARD" list _devices/HiFi 2>&1)" || true
echo "$UCM_DEVS" | sed 's/^/    /'
if ! echo "$UCM_DEVS" | grep -qw 'Speaker'; then
  echo
  echo "    diagnostics:" >&2
  echo "      installed override : $OVERRIDE" >&2
  echo "      exists             : $([ -f "$OVERRIDE" ] && echo yes || echo NO)" >&2
  echo "      CardLongName       : $LONG" >&2
  echo "      components         : ${COMPONENTS:-(empty)}" >&2
  fail "UCM still exposes no Speaker device for card $CARD.
    This is exactly the silent failure this installer now refuses to hide.
    Re-run with the long name forced if you believe the probe is wrong:
      PX13_LONGNAME='<name>' bash install-durable.sh
    and open an issue with the diagnostics above."
fi
echo "    OK - Speaker device present"

echo "==> 5/8 Restarting PipeWire and selecting the HiFi profile"
systemctl --user restart wireplumber pipewire pipewire-pulse
sleep 3
PCARD="$(px13_pw_card)" || true
if [ -n "${PCARD:-}" ]; then
  echo "    PipeWire card: $PCARD"
  pactl set-card-profile "$PCARD" HiFi 2>/dev/null || echo "    (profile switch failed - check 'pactl list cards')"
else
  echo "    WARNING: no SoundWire card in PipeWire yet"
fi
sleep 2

echo "==> 6/8 State (expected: Attached, channels 1/2, Speaker sink)"
echo "    soundwire:$(px13_sdw_status_str)"
AMPS="$(px13_amp_count "$CARD")"
for n in $(seq 1 "${AMPS:-0}"); do
  amixer -D "hw:$CARD" cget name="tas2783-$n Channel Playback" 2>/dev/null | tail -1 | sed "s/^/    tas2783-$n:/"
done
[ "${AMPS:-0}" -lt 2 ] && echo "    note: only $AMPS amp(s) with controls - stereo assignment skipped"
wpctl status | sed -n '/Sinks:/,/Sources:/p' | sed 's/^/    /'
if SPK="$(px13_pw_speaker_sink)"; then
  wpctl set-default "$(pactl list short sinks | awk -v s="$SPK" '$2 == s { print $1; exit }')" 2>/dev/null || true
  echo "    default sink = $SPK"
fi

echo "==> 7/8 Persisting the ALSA state"
sudo alsactl store || true

echo "==> 8/8 Done"
echo
if [ "$NEED_REBOOT" = 1 ]; then
  echo "REBOOT, then run: speaker-test -D pulse -c2 -l1 -t wav"
else
  echo "SOUND TEST (stereo: 'Front Left' on the left, 'Front Right' on the right):"
  speaker-test -D pulse -c2 -l1 -t wav 2>/dev/null | grep Front || true
  echo
  echo "If the sides come out swapped, swap the two csets in"
  echo "  $UCM/sof-soundwire/tas2783.conf  (1 <-> 2)  and run:"
  echo "  systemctl --user restart pipewire wireplumber"
fi
echo
echo "Suspend/resume recovery is a separate, optional step:"
echo "  bash install-resume-recovery.sh"
